server:
  port: 7777
spring:
  datasource:
    username: root
    password: 151463
    url: jdbc:mysql://localhost:3306/mh_blog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    host: 192.168.153.104  # 地址
    port: 6379  # 端口
    password: 151463  # 密码
    database: 0  # redis 数据库索引，默认为0

# 配置mybatis-plus
mybatis-plus:
  configuration:
    # 开启mp日志（输出到控制台）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 注册mapper.xml配置文件
  mapper-locations: classpath:mapper/*.xml
  # 别名
  type-aliases-package: com.mohan.domain.vo
  global-config:
    db-config:
      # 配置全局的id生成策略，默认使用雪花算法
      id-type: auto
      # 配置全局的逻辑删除字段，0 没删除，1 删除
      logic-delete-field: delFlag
      logic-not-delete-value: 0
      logic-delete-value: 1
    banner: false

oss:
  accessKey: CPHKQwIzdgLdaFjvKqjZLL_tWPDEosioUrFSepia
  secretKey: g8bfatlhlBF-y_7RcsdtQC7mtGRtxvLmwANa8_7V
  bucket: mh-blog-image
  url: http://rray0ungs.hn-bkt.clouddn.com/
